#  -----------------------------------------------------------------------
#     Default values for the tape recall scheduler
#  -----------------------------------------------------------------------
@DEFAULTS_HEADER@
#
#  The tape recall scheduler is the component that clusters and schedules requests
#  that target tape-resident data according to a set of rules before
#  requesting their recall from tape inorder to optimize the performance.

#
# Cell name
#
taperecallscheduler.cell.name=taperecallscheduler

#  ----- Whether the service is replicable
#
#   Any service in dCache can have several instances as long as these
#   represent separate logical services. Some services can have several
#   instances representing the same logical service, providing some
#   degree of fault tolerance and load balancing. Such services are said
#   to be replicable.
#
#   Instances of a logical service share the same service name, and it is
#   important that the configuration for such instances is synchronized.
#
#   This property indicates if this service is replicable.
#
(immutable)taperecallscheduler.cell.replicable = false

# ---- Request scheduling strategy for bring-online requests
#
# If enabled, this strategy controls in which order tape recall requests
# are sent to the tape system.
# If disabled, tape recall requests are handled as usual
#
(one-of?true|false)taperecallscheduler.cell.enable = false

#
# Directory to look for tape info files
#
taperecallscheduler.tapeinfo-dir = ${dcache.paths.tapeinfo}

#
# Max number of tapes for which to pass on requests in parallel,
# which is usually equal to the number of available drives
#
taperecallscheduler.num-drives = 1

#
# Min targeted tape capacity percentage required before passing on requests
#
taperecallscheduler.min-tape-recall-percentage = 60

#
# Min number of requests for a tape before being selected if min-tape-recall-percentage is not fulfilled.
# A value of -1 indicates that the request count for a tap-e will not be taken into account.
#
taperecallscheduler.min-request-count-for-tape = 1000

#
# Min time a request needs to remain in the queue before the tape is being selected. The goal is to
# wait until no more requests are actively arriving for a tape in order to maximize the recall
#
taperecallscheduler.min-time-in-queue = 2
(one-of?MILLISECONDS|SECONDS|MINUTES|HOURS)\
taperecallscheduler.min-time-in-queue.unit = MINUTES

#
# Max time a request is allowed to remain in the queue. A larger number allows for better clustering,
# but will also require more memory and might lead to longer overall waiting times for a tape
#
taperecallscheduler.max-time-in-queue = 1
(one-of?MILLISECONDS|SECONDS|MINUTES|HOURS|DAYS)\
taperecallscheduler.max-time-in-queue.unit = HOURS